### ISSUE TITLE
[BUG] Errors thrown on install even in blank repo

### ISSUE THREAD

**Issue by bmcilw1** [flowaccount/nx-plugins#66]
**Describe the bug**

Dependency resolution errors are thrown on install.

**To Reproduce**

```bash
mkdir test-nx-sls
cd test-nx-sls
npx create-nx-workspace test --preset=angular --nx-cloud=false --linter=eslint --style=css --appName=testapp
cd test
nx add @flowaccount/nx-serverless
```

**Expected behavior**

Package install should succeed on a fresh install.

**Throws error**

```text
nx add @flowaccount/nx-serverless
? Would you like to share anonymous usage data about this project with the Angul
ar Team at
Google under Google’s Privacy Policy at https://policies.google.com/privacy? For
 more
details and how to change this setting, see http://angular.io/analytics. No
Installing packages for tooling via npm.
An unhandled exception occurred: npm WARN deprecated core-js@2.6.12: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated viz.js@1.8.2: no longer supported
npm WARN deprecated axios@0.19.2: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410
npm WARN deprecated @types/chalk@2.2.0: This is a stub types definition for chalk (https://github.com/chalk/chalk). chalk provides its own type definitions, so you don't need @types/chalk installed!


┌─────────────────────────────────────────────────────────────┐
│                                                             │
│   The package prisma has been renamed to prisma1.           │
│                                                             │
│   Please uninstall prisma.                                  │
│   Then install prisma1 to continue using Prisma 1:          │
│                                                             │
│      # Uninstall old CLI                                    │
│      npm uninstall -g prisma                                │
│                                                             │
│      # Install new CLI                                      │
│      npm install -g prisma1                                 │
│                                                             │
│      # Invoke via global `prisma1` command                  │
│      prisma1 --help                                         │
│                                                             │
│   Learn more here:                                          │
│   https://github.com/prisma/prisma1/releases/tag/1.34.12    │
│                                                             │
│   Prisma 1 is in maintenance mode.                          │
│   We recommend to check out Prisma 2:                       │
│   http://pris.ly/d/upgrading-to-prisma2                     │
│                                                             │
└─────────────────────────────────────────────────────────────┘



npm WARN @angular-eslint/eslint-plugin@1.0.0 requires a peer of eslint-plugin-import@* but none is installed. You must install peer dependencies yourself.
npm WARN @angular-eslint/eslint-plugin@1.0.0 requires a peer of eslint-plugin-jsdoc@* but none is installed. You must install peer dependencies yourself.
npm WARN @angular-eslint/eslint-plugin@1.0.0 requires a peer of eslint-plugin-prefer-arrow@* but none is installed. You must install peer dependencies yourself.
npm WARN @ngtools/webpack@8.3.14 requires a peer of @angular/compiler-cli@^8.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @angular-devkit/build-angular@0.803.14 requires a peer of @angular/compiler-cli@^8.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN fork-ts-checker-webpack-plugin@0.4.15 requires a peer of tslint@^4.0.0 || ^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @angular-devkit/build-ng-packagr@0.803.14 requires a peer of ng-packagr@^4.0.0 || ^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @nrwl/node@8.8.3 requires a peer of @nrwl/workspace@8.8.3 but none is installed. You must install peer dependencies yourself.
npm WARN @nrwl/jest@8.8.3 requires a peer of @nrwl/workspace@8.8.3 but none is installed. You must install peer dependencies yourself.
npm WARN @nrwl/linter@8.8.3 requires a peer of @nrwl/workspace@8.8.3 but none is installed. You must install peer dependencies yourself.
npm WARN fork-ts-checker-webpack-plugin@0.4.15 requires a peer of tslint@^4.0.0 || ^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN fork-ts-checker-webpack-plugin@0.4.15 requires a peer of typescript@^2.1.0 || ^3.0.0 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! prisma@1.34.12 preinstall: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the prisma@1.34.12 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/brianmcilwain/.npm/_logs/2021-01-25T15_44_26_873Z-debug.log
Package install failed, see above.
See "/private/var/folders/r8/5tt87lwn71z4679z4gkkt6880000gn/T/ng-sTE1NW/angular-errors.log" for further details.
```

**Check which provider is affected:**
[x] AWS
[x] Azure
[x] Google Cloud Platform

**Check which framework is affected:**
[x] Angular
[x] Nodejs
[x] Serverless
[x] Lambda
[] Infrastructure as a code

All are affected as the package cannot currently be successfully installed due to now non-existent packages.

```text
nx report 

>  NX  Report complete - copy this into the issue template

  Node : 14.15.4
  OS   : darwin x64
  npm  : 6.14.10
  
  nx : Not Found
  @nrwl/angular : 11.1.5
  @nrwl/cli : 11.1.5
  @nrwl/cypress : 11.1.5
  @nrwl/devkit : 11.1.5
  @nrwl/eslint-plugin-nx : 11.1.5
  @nrwl/express : Not Found
  @nrwl/jest : 11.1.5
  @nrwl/linter : 11.1.5
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 8.8.3
  @nrwl/react : Not Found
  @nrwl/schematics : 8.8.3
  @nrwl/tao : 11.1.5
  @nrwl/web : Not Found
  @nrwl/workspace : 11.1.5
  typescript : 4.0.5

```

**Comment by wickstargazer** [comment]
Hi! i have fixed the init function for nx-serverless to serve better and default as an api which will be released in v0.5.3

also i dont get the above error how does `prisma` comes into play since there is no reference to it in nx-serverless

**Comment by wickstargazer** [comment]
Hi would it be possible to look at this in 1.0.0-beta.2 if it works? @bmcilw1

**Comment by bmcilw1** [comment]
Hi @wickstargazer, great job with this! I'll be happy to take a look at some point when we prioritize it on our end.

In the meantime, I've been using [serverless-plugin-optimize](https://github.com/FidelLimited/serverless-plugin-optimize)

Great work again on your plugin!

**Comment by bmcilw1** [comment]
Hi @wickstargazer!

Thanks again for your great work here. As Webpack keeps getting updates, eventually our copy of [serverless-plugin-optimize](https://github.com/FidelLimited/serverless-plugin-optimize) started having issues. So, we're re-prioritizing time to looking into other solutions.

I've been able to run `npm install @flowaccount/nx-serverless --save-dev` in our main repo without issue, so that's great.

**Comment by bmcilw1** [comment]
So this still does not work with your latest updates

```zsh
mkdir test-nx-sls
cd test-nx-sls
brianmcilwain@Brians-MacBook-Pro test-nx-sls % npx create-nx-workspace test --preset=angular --nx-cloud=false --linter=eslint --style=css --appName=testapp
npx: installed 48 in 5.885s

>  NX  Nx is creating your workspace.

  To make sure the command works reliably in all environments, and that the preset is applied correctly,
  Nx will run "npm install" several times. Please wait.

✔ Installing dependencies with npm
✔ Nx has successfully created the workspace.

———————————————————————————————————————————————


>  NX   NOTE  First time using Nx? Check out this interactive Nx tutorial.

  https://nx.dev/latest/angular/tutorial/01-create-application
  
  Prefer watching videos? Check out this free Nx course on YouTube.
  https://www.youtube.com/watch?v=2mYLe9Kp9VM&list=PLakNactNC1dH38AfqmwabvOszDmKriGco

brianmcilwain@Brians-MacBook-Pro test-nx-sls % cd test 
brianmcilwain@Brians-MacBook-Pro test % nx add @flowaccount/nx-serverless
? Would you like to share anonymous usage data about this project with the Angul
ar Team at
Google under Google’s Privacy Policy at https://policies.google.com/privacy? For
 more
details and how to change this setting, see https://angular.io/analytics. No
ℹ Using package manager: npm
✔ Found compatible package version: @flowaccount/nx-serverless@1.0.0-beta.3.
✔ Package information loaded.
 
The package @flowaccount/nx-serverless@1.0.0-beta.3 will be installed and execut
ed.
Would you like to proceed? Yes
✔ Package successfully installed.
An unhandled exception occurred: Schematic "init" cannot resolve the factory.
See "/private/var/folders/r8/5tt87lwn71z4679z4gkkt6880000gn/T/ng-vn7BiN/angular-errors.log" for further details.
brianmcilwain@Brians-MacBook-Pro test % 

```

**Comment by wickstargazer** [comment]
does `1.0.0-beta.5` solves your problem? 
https://github.com/flowaccount/nx-plugins/pull/91

**Comment by bmcilw1** [comment]
Hi @wickstargazer. I came back around to give this another try. Unfortunatly, things are still broken 😞 

```sh
brianmcilwain@Brians-MacBook-Pro source % mkdir test-nx-sls && cd test-nx-sls
brianmcilwain@Brians-MacBook-Pro test-nx-sls % npx create-nx-workspace test --preset=angular --nx-cloud=false --linter=eslint --style=css --appName=testapp
npx: installed 48 in 4.089s

>  NX  Nx is creating your v13.3.6 workspace.

  To make sure the command works reliably in all environments, and that the preset is applied correctly,
  Nx will run "npm install" several times. Please wait.

✔ Installing dependencies with npm
✔ Nx has successfully created the workspace.

———————————————————————————————————————————————


>  NX   NOTE  First time using Nx? Check out this interactive Nx tutorial.

  https://nx.dev/latest/angular/tutorial/01-create-application
  
  Prefer watching videos? Check out this free Nx course on YouTube.
  https://www.youtube.com/watch?v=2mYLe9Kp9VM&list=PLakNactNC1dH38AfqmwabvOszDmKriGco

brianmcilwain@Brians-MacBook-Pro test-nx-sls % cd test 
brianmcilwain@Brians-MacBook-Pro test % nx add @flowaccount/nx-serverless
Ng add is not natively supported by Nx
Instead, we recommend running `npm install @flowaccount/nx-serverless && npx nx g @flowaccount/nx-serverless:ng-add`
✔ Run this command? (y/N) · false
brianmcilwain@Brians-MacBook-Pro test % nx add @flowaccount/nx-serverless
Ng add is not natively supported by Nx
Instead, we recommend running `npm install @flowaccount/nx-serverless && npx nx g @flowaccount/nx-serverless:ng-add`
✔ Run this command? (y/N) · true

npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
npm WARN deprecated @hapi/boom@7.4.11: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/hapi@18.4.1: This version contains severe security issues and defects and should not be used! Please upgrade to the latest version of @hapi/hapi or consider a commercial license (https://github.com/hapijs/hapi/issues/4114)
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/joi@16.1.8: Switch to 'npm install joi'
npm WARN deprecated @hapi/wreck@15.1.0: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/formula@1.2.0: Moved to 'npm install @sideway/formula'
npm WARN deprecated @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
npm WARN deprecated @hapi/pinpoint@1.0.2: Moved to 'npm install @sideway/pinpoint'
npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/joi@15.1.1: Switch to 'npm install joi'
npm WARN deprecated @hapi/accept@3.2.4: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/catbox@10.2.3: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/call@5.1.3: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/ammo@3.1.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/shot@4.1.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/bounce@1.3.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/mimos@4.1.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/heavy@6.2.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/catbox-memory@4.1.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/podium@3.4.3: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/teamwork@3.3.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/somever@2.1.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/statehood@6.1.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/subtext@6.1.3: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/iron@5.1.4: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/cryptiles@4.2.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/b64@4.2.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/pez@4.1.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/content@4.1.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/file@1.0.0: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/nigel@3.1.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/vise@3.1.1: This version has been deprecated and is no longer supported or maintained

> fsevents@1.2.13 install /Users/brianmcilwain/source/test-nx-sls/test/node_modules/@flowaccount/nx-serverless/node_modules/fsevents
> node install.js

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node

> fsevents@1.2.13 install /Users/brianmcilwain/source/test-nx-sls/test/node_modules/watchpack-chokidar2/node_modules/fsevents
> node install.js

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node

> snappy@6.3.5 install /Users/brianmcilwain/source/test-nx-sls/test/node_modules/snappy
> prebuild-install || node-gyp rebuild


> protobufjs@6.11.2 postinstall /Users/brianmcilwain/source/test-nx-sls/test/node_modules/protobufjs
> node scripts/postinstall


> serverless@2.69.1 postinstall /Users/brianmcilwain/source/test-nx-sls/test/node_modules/serverless
> node ./scripts/postinstall.js


   ┌───────────────────────────────────────────────────┐
   │                                                   │
   │   Serverless Framework successfully installed!    │
   │                                                   │
   │   To start your first project run “serverless”.   │
   │                                                   │
   └───────────────────────────────────────────────────┘

npm WARN ajv-keywords@3.5.2 requires a peer of ajv@^6.9.1 but none is installed. You must install peer dependencies yourself.
npm WARN jasmine-marbles@0.8.4 requires a peer of rxjs@^6.5.3 but none is installed. You must install peer dependencies yourself.
npm WARN rxjs-for-await@0.0.2 requires a peer of rxjs@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @flowaccount/nx-serverless@1.0.2 requires a peer of @nrwl/workspace@^12.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-windows-arm64@0.13.13 (node_modules/jest-preset-angular/node_modules/esbuild-windows-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-windows-arm64@0.13.13: wanted {"os":"win32","arch":"arm64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-windows-64@0.13.13 (node_modules/jest-preset-angular/node_modules/esbuild-windows-64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-windows-64@0.13.13: wanted {"os":"win32","arch":"x64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-windows-32@0.13.13 (node_modules/jest-preset-angular/node_modules/esbuild-windows-32):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-windows-32@0.13.13: wanted {"os":"win32","arch":"ia32"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-sunos-64@0.13.13 (node_modules/jest-preset-angular/node_modules/esbuild-sunos-64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-sunos-64@0.13.13: wanted {"os":"sunos","arch":"x64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-openbsd-64@0.13.13 (node_modules/jest-preset-angular/node_modules/esbuild-openbsd-64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-openbsd-64@0.13.13: wanted {"os":"openbsd","arch":"x64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-netbsd-64@0.13.13 (node_modules/jest-preset-angular/node_modules/esbuild-netbsd-64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-netbsd-64@0.13.13: wanted {"os":"netbsd","arch":"x64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-linux-ppc64le@0.13.13 (node_modules/jest-preset-angular/node_modules/esbuild-linux-ppc64le):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-linux-ppc64le@0.13.13: wanted {"os":"linux","arch":"ppc64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-linux-mips64le@0.13.13 (node_modules/jest-preset-angular/node_modules/esbuild-linux-mips64le):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-linux-mips64le@0.13.13: wanted {"os":"linux","arch":"mips64el"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-linux-arm64@0.13.13 (node_modules/jest-preset-angular/node_modules/esbuild-linux-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-linux-arm64@0.13.13: wanted {"os":"linux","arch":"arm64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-linux-arm@0.13.13 (node_modules/jest-preset-angular/node_modules/esbuild-linux-arm):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-linux-arm@0.13.13: wanted {"os":"linux","arch":"arm"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-linux-64@0.13.13 (node_modules/jest-preset-angular/node_modules/esbuild-linux-64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-linux-64@0.13.13: wanted {"os":"linux","arch":"x64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-linux-32@0.13.13 (node_modules/jest-preset-angular/node_modules/esbuild-linux-32):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-linux-32@0.13.13: wanted {"os":"linux","arch":"ia32"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-freebsd-arm64@0.13.13 (node_modules/jest-preset-angular/node_modules/esbuild-freebsd-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-freebsd-arm64@0.13.13: wanted {"os":"freebsd","arch":"arm64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-freebsd-64@0.13.13 (node_modules/jest-preset-angular/node_modules/esbuild-freebsd-64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-freebsd-64@0.13.13: wanted {"os":"freebsd","arch":"x64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-darwin-arm64@0.13.13 (node_modules/jest-preset-angular/node_modules/esbuild-darwin-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-darwin-arm64@0.13.13: wanted {"os":"darwin","arch":"arm64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-android-arm64@0.13.13 (node_modules/jest-preset-angular/node_modules/esbuild-android-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-android-arm64@0.13.13: wanted {"os":"android","arch":"arm64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-windows-arm64@0.13.12 (node_modules/esbuild-windows-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-windows-arm64@0.13.12: wanted {"os":"win32","arch":"arm64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-windows-64@0.13.12 (node_modules/esbuild-windows-64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-windows-64@0.13.12: wanted {"os":"win32","arch":"x64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-windows-32@0.13.12 (node_modules/esbuild-windows-32):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-windows-32@0.13.12: wanted {"os":"win32","arch":"ia32"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-sunos-64@0.13.12 (node_modules/esbuild-sunos-64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-sunos-64@0.13.12: wanted {"os":"sunos","arch":"x64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-openbsd-64@0.13.12 (node_modules/esbuild-openbsd-64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-openbsd-64@0.13.12: wanted {"os":"openbsd","arch":"x64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-netbsd-64@0.13.12 (node_modules/esbuild-netbsd-64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-netbsd-64@0.13.12: wanted {"os":"netbsd","arch":"x64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-linux-ppc64le@0.13.12 (node_modules/esbuild-linux-ppc64le):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-linux-ppc64le@0.13.12: wanted {"os":"linux","arch":"ppc64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-linux-mips64le@0.13.12 (node_modules/esbuild-linux-mips64le):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-linux-mips64le@0.13.12: wanted {"os":"linux","arch":"mips64el"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-linux-arm64@0.13.12 (node_modules/esbuild-linux-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-linux-arm64@0.13.12: wanted {"os":"linux","arch":"arm64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-linux-arm@0.13.12 (node_modules/esbuild-linux-arm):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-linux-arm@0.13.12: wanted {"os":"linux","arch":"arm"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-linux-64@0.13.12 (node_modules/esbuild-linux-64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-linux-64@0.13.12: wanted {"os":"linux","arch":"x64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-linux-32@0.13.12 (node_modules/esbuild-linux-32):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-linux-32@0.13.12: wanted {"os":"linux","arch":"ia32"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-freebsd-arm64@0.13.12 (node_modules/esbuild-freebsd-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-freebsd-arm64@0.13.12: wanted {"os":"freebsd","arch":"arm64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-freebsd-64@0.13.12 (node_modules/esbuild-freebsd-64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-freebsd-64@0.13.12: wanted {"os":"freebsd","arch":"x64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-darwin-arm64@0.13.12 (node_modules/esbuild-darwin-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-darwin-arm64@0.13.12: wanted {"os":"darwin","arch":"arm64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-android-arm64@0.13.12 (node_modules/esbuild-android-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-android-arm64@0.13.12: wanted {"os":"android","arch":"arm64"} (current: {"os":"darwin","arch":"x64"})

+ @flowaccount/nx-serverless@1.0.2
added 1198 packages from 648 contributors, removed 1 package and audited 2749 packages in 63.797s

182 packages are looking for funding
  run `npm fund` for details

found 17 vulnerabilities (8 moderate, 9 high)
  run `npm audit fix` to fix them, or `npm audit` for details
Schematic "init" cannot resolve the factory.
(node:6309) UnhandledPromiseRejectionWarning: Error: Command failed: npm install @flowaccount/nx-serverless && npx nx g @flowaccount/nx-serverless:ng-add
    at checkExecSyncError (child_process.js:616:11)
    at execSync (child_process.js:652:15)
    at /Users/brianmcilwain/source/test-nx-sls/test/node_modules/@nrwl/cli/lib/init-local.js:72:54
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:6309) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:6309) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

You can see a few changes in the log, but the main issue is still at the bottom

```
Schematic "init" cannot resolve the factory.
(node:6309) UnhandledPromiseRejectionWarning: Error: Command failed: npm install @flowaccount/nx-serverless && npx nx g @flowaccount/nx-serverless:ng-add
    at checkExecSyncError (child_process.js:616:11)
    at execSync (child_process.js:652:15)
    at /Users/brianmcilwain/source/test-nx-sls/test/node_modules/@nrwl/cli/lib/init-local.js:72:54
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```
